variable "ami_id" {}
variable "instance_type" {}
variable "vpc_security_group_ids" {}
variable "zone_id" {}
variable "tag_name" {}
variable "env" {}
variable "vault_token" {}
#variable "ansible_role" {}
variable "key_name" {}
